const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

const MY_ORDER_REQUEST = "MY_ORDER_REQUEST"
const MY_ORDER_SUCCESS = "MY_ORDER_SUCCESS"
const MY_ORDER_FAIL = "MY_ORDER_FAIL"

const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST"
const ALL_ORDER_SUCCESS = "ALL_ORDER_SUCCESS"
const ALL_ORDER_FAIL = "ALL_ORDER_FAIL"

const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST"
const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS"
const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL"
const UPDATE_ORDER_RESET= "UPDATE_ORDER_RESET"

const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"
const DELETE_ORDER_RESET= "DELETE_ORDER_RESET"






const CLEAR_ERROR = "CLEAR_ERROR"

export{
    CREATE_ORDER_FAIL,
    CREATE_ORDER_SUCCESS,
    CREATE_ORDER_REQUEST,
    CLEAR_ERROR,
    MY_ORDER_FAIL,
    MY_ORDER_REQUEST,
    MY_ORDER_SUCCESS,
    ORDER_DETAILS_FAIL,
    ORDER_DETAILS_REQUEST,
    ORDER_DETAILS_SUCCESS,
    ALL_ORDER_REQUEST,
    ALL_ORDER_SUCCESS,
    ALL_ORDER_FAIL,
    UPDATE_ORDER_REQUEST,
    UPDATE_ORDER_SUCCESS,
    UPDATE_ORDER_FAIL,
    UPDATE_ORDER_RESET,
    DELETE_ORDER_REQUEST,
    DELETE_ORDER_SUCCESS,
    DELETE_ORDER_FAIL,
    DELETE_ORDER_RESET,
}